name: Build, Test, and Push Docker Images

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Flask API Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./hubitat_lock_manager/Dockerfile.api
          tags: |
            ghcr.io/${{ github.repository_owner }}/flask-api:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/flask-api:latest
          build-args:
            TAG: ${{ github.ref_name }}
          push: true

      - name: Build Streamlit UI Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./hubitat_lock_manager/Dockerfile.ui
          tags: |
            ghcr.io/${{ github.repository_owner }}/streamlit-ui:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/streamlit-ui:latest
          build-args:
            TAG: ${{ github.ref_name }}
          push: true

      - name: Test Docker images
        run: |
          curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
          chmod +x container-structure-test-linux-amd64
          ./container-structure-test-linux-amd64 test --image ghcr.io/${{ github.repository_owner }}/flask-api:${{ github.ref_name }} --config tests/container-test.yaml
          ./container-structure-test-linux-amd64 test --image ghcr.io/${{ github.repository_owner }}/streamlit-ui:${{ github.ref_name }} --config tests/container-test.yaml
