name: Build and Push Docker Images

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Flask API Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.api
          tags: |
            yourdockerhubusername/flask-api:${{ github.ref_name }}
            yourdockerhubusername/flask-api:latest
          push: true

      - name: Build and push Streamlit UI Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.ui
          tags: |
            yourdockerhubusername/streamlit-ui:${{ github.ref_name }}
            yourdockerhubusername/streamlit-ui:latest
          push: true
