name: Semantic Version and Publish

on:
  push:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure the full history is included

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools

      - name: Semantic Version
        id: version
        uses: paulhatch/semantic-version@v5.3.0
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
      version_format: "${major}.${minor}.${patch}-prerelease${increment}"
      enable_prerelease_mode: true

      - name: Update Version in version.py
        run: python update_version.py ${{ steps.version.outputs.version_tag }}

      - name: Set up Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Commit Changes
        run: |
          git add hubitat_lock_manager/version.py
          git commit -m "chore: update version to ${{ steps.version.outputs.version_tag }}"
          git push origin main

      - name: Push Tag
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        run: |
          git tag ${{ steps.version.outputs.version_tag }}
          git push https://$GITHUB_ACTOR:${{ secrets.ACTIONS_TOKEN }}@github.com/${{ github.repository }} --tags

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Flask API Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./hubitat_lock_manager/Dockerfile.api
          tags: |
            ghcr.io/${{ github.repository_owner }}/flask-api:${{ steps.version.outputs.version_tag }}
            ghcr.io/${{ github.repository_owner }}/flask-api:latest
          build-args:
            TAG: ${{ steps.version.outputs.version_tag }}
          push: true

      - name: Build and push Streamlit UI Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./hubitat_lock_manager/Dockerfile.ui
          tags: |
            ghcr.io/${{ github.repository_owner }}/streamlit-ui:${{ steps.version.outputs.version_tag }}
            ghcr.io/${{ github.repository_owner }}/streamlit-ui:latest
          build-args:
            TAG: ${{ steps.version.outputs.version_tag }}
          push: true

      - name: Test Docker images
        run: |
          curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
          chmod +x container-structure-test-linux-amd64
          ./container-structure-test-linux-amd64 test --image ghcr.io/${{ github.repository_owner }}/flask-api:${{ steps.version.outputs.version_tag }} --config tests/container-test.yaml
          ./container-structure-test-linux-amd64 test --image ghcr.io/${{ github.repository_owner }}/streamlit-ui:${{ steps.version.outputs.version_tag }} --config tests/container-test.yaml
