name: Semantic Version

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensure the full history is included

      - name: Semantic Version
        id: version
        uses: paulhatch/semantic-version@v5.3.0
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${major}.${minor}.${patch}-prerelease${increment}"
          enable_prerelease_mode: true

      - name: Create Release Tag
        if: github.event_name == 'push'
        run: |
          git tag ${{ steps.version.outputs.version_tag }}
          git push origin --tags
